#!/usr/bin/env bash
# Configuring Nginx on a fresh Ubuntu machine to inject a custom

set -e


apt-get update -y || true
apt-get install -y nginx

NGINX_CONF="/etc/nginx/nginx.conf"
HEADER_LINE="add_header X-Served-By \$hostname always;"


if ! grep -qF "X-Served-By" "$NGINX_CONF"; then
    sed -i "/http {/a \\\t${HEADER_LINE}" "$NGINX_CONF"
fi

nginx -t
service nginx restart
