#!/usr/bin/env bash
# Configures an Ubuntu machine to install and configure HAProxy

apt-get update -y
apt-get install -y haproxy

cat >> /etc/haproxy/haproxy.cfg <<EOF

frontend balancer_http
    bind *:80
    mode http
    default_backend webservers

backend webservers
    mode http
    balance roundrobin
    server web-01 100.24.4.34:80 check
    server web-02 44.201.163.226:80 check
EOF

echo "ENABLED=1" > /etc/default/haproxy

service haproxy restart
