#!/usr/bin/env bash
# this script redirects after making nginx
apt-get -y update
apt-get -y install nginx

sed -i '/location \/ {/,/}/c\
    location / {\
        rewrite ^/redirect_me/?$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\
        try_files $uri $uri/ =404;\
    }' /etc/nginx/sites-available/default

service nginx restart
