#!/usr/bin/env bash
# redirection
apt-get update -y
apt-get install -y nginx

NGINX_CONF="/etc/nginx/sites-available/default"


if ! grep -q "location /redirect_me" "$NGINX_CONF"; then
    sed -i '0,/^}/s//\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}\n}/' "$NGINX_CONF"
fi


service nginx restart
