#!/usr/bin/env bash
# redirecting to a permanent website

apt-get update
apt-get install -y nginx

sed -i '/server_name _;/a \    rewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

service nginx restart
