#!/usr/bin/env bash
# 4-not_found_page_404


apt-get update -y
apt-get install -y nginx


NGINX_CONF="/etc/nginx/sites-available/default"


echo "Ceci n'est pas une page" > /var/www/html/404.html


if ! grep -q "location /redirect_me" "$NGINX_CONF"; then
    sed -i '0,/^}/s//\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}\n}/' "$NGINX_CONF"
fi

if ! grep -q "error_page 404" "$NGINX_CONF"; then
    sed -i '0,/^}/s//\terror_page 404 \/404.html;\n}/' "$NGINX_CONF"
fi

service nginx restart
